[build]
  base = "frontend/"
  publish = "frontend/dist/"
  command = "npm run build"
  environment = { NODE_VERSION = "16" }

# Redirect API requests to your backend (if you're using Netlify Functions)
[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200 