[build]
  base = "frontend/"
  publish = "dist/"
  command = "npm run build"

# Redirect API requests to your backend (if you're using Netlify Functions)
[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200 